### ISSUE TITLE
'quasar' should be listed in the project's dependencies

### ISSUE THREAD

**Issue by purell** [quasarframework/quasar-future#1]
Hi,

I'm trying to use [quasar-futur](https://github.com/quasarframework/quasar-future) to evaluate the new QTable but I'm stuck on this error when I execute `quasar build`

```
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'quasar' in 'D:\test\client\src'
 @ ./src/main.js 6:0-28

'quasar' should be listed in the project's dependencies. Run 'npm i -S quasar' to add it
```

But I already installed quasar-futur using npm
```
npm i --save git+https://git@github.com/quasarframework/quasar-future.git 
```

In my package.json I have
```
 "dependencies": {
    "babel-runtime": "^6.25.0",
    "quasar-extras": "^0.0.8",
    "quasar-framework": "git+https://git@github.com/quasarframework/quasar-future.git",
    "vue": "^2.5.0",
    "vue-i18n": "^7.3.2",
    "vue-router": "^3.0.1",
    "vuelidate": "^0.6.1",
    "vuex": "^3.0.0"
  },
```

On my `main.js` I leave the import as they were before on version 0.14. I mean what the CLI (default-template) contains.
```
import Quasar from 'quasar';
```

So I look into `node_modules/quasar-framework/package.json` and I saw
```
"main": "dist/quasar.esm.js",
"module": "dist/quasar.esm.js",
```

But obviously those file does not exists in the repo https://github.com/quasarframework/quasar-edge/tree/master/dist. We now have `quasar.mat.esm.js` and `quasar.mat.umd.js`.

Thus, do I'm doing something wrong ? 

Honestly, this is my last attempt to evaluate Quasar, before migrating to another framework, because I have to be 100% sure that the new QTable suits my needs. This is a critical component for the application and the one in the version 0.14 does not work at all for dynamic columns.

If everything works well, be assured that I will contribute to the evolution of quasar thereafter. It will be a pleasure.

Thank you for your help.

**Comment by rstoenescu** [comment]
Hi,

This is because the starter kit needs some changes. What you can do is this:
1. `$ quasar init default#v0.15-wip <folder>` (uses this "future" version by default - v0.15 currently)
2. Clone default Quasar repo and run "npm run dev". The new datatable is on "data-table" and "data-table2" pages. Take a good look at the examples. Do not simply copy the usage from v0.14 datatable as the new one works very different.

Mind that the "future" version can change API at any moment without any notice. It is still work in progress (although almost finalised). For example, QLayout will suffer some minor changes (if you wanna take a peek - "new layout" page on Quasar repo dev).

Tell me if you find any bugs. Thanks and hope you enjoy Quasar!
PS: Be sure to switch to the official v0.15 version once it is released.

**Comment by purell** [comment]
Hi @rstoenescu

Thank you so much for your help, its really **appreciated**.

I finally succeed to to make it all working with **0.15**. I've done some test on the new data-table. First of all dynamics columns are now working pefectly. Thank.

But there something I'm no longer able to do, I want my first column to display an icon.
```
data() {
    return {
      columns: [
        {
          label: "Graph",
          name: "graph",
          format: function() {
            return '<i class="material-icons text-positive" style="font-size: 22px">info</i>';
          }
      ],
```

But the resulting html seems to be escaped
![image](https://user-images.githubusercontent.com/7946730/32116194-a350a6e0-bb17-11e7-8a53-5a1d3aa43b60.png)

I look into the source code https://github.com/quasarframework/quasar/blob/dev/src/components/table/table-body.js#L108 and try to set the `field` property to a function 
```
data() {
    return {
      columns: [
        {
          label: "Graph",
          name: "graph",
          field: function() {
            return '<i class="material-icons text-positive" style="font-size: 22px">info</i>';
          }
      ],
```

But it's the same result, escaped HTML. Is there something special to prevent HTML escaping ?

I can open a new issue if your prefer, let me know.
Best regards,

**Comment by rstoenescu** [comment]
`body-cell-{col.name}` is especially for these cases where you want to display custom content. What do you mean by "HTML into the column that will probably not be possible with slot mechanism". Give one example.

Also, use QIcon instead of plain old "<i>".

The new datatable works differently than the old one and cannot accomodate the same "responsiveness" as the old one. User is able to pan horizontally though. On narrow windows the content becomes more "compact". This is by default.

**Comment by purell** [comment]
Hi @rstoenescu 

There **one more thing** that I'm having difficulty to migrate. In the 0.14, I was including quasar stylus variables

#### Login.vue
```jsx
<style lang="stylus">
@import '~variables';    //////// <------ Invalid import
.background {
  background-color: $primary;
}
</style>
```

Now, I'm getting the following error
```
ERROR in ./node_modules/css-loader?{"minimize":true,"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0e596401","scoped":false,"hasInlineConfig":false}
!./node_modules/stylus-loader?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Login.vue
Module build failed: Error: D:\client\src\components\Login.vue:202:9
   202| @import '~variables';
----------------^
```

I tried without the tild (~) before the path but it does not work. Did I miss something ?

I look to the file [build/webpack.base.conf.js](https://github.com/quasarframework/quasar-template-default/blob/v0.15-wip/template/build/webpack.base.conf.js#L43) the alias `variables` is well declared but into a `merge` object ?

In the old version 0.14 you had an alias in the file https://github.com/quasarframework/quasar-template-default/blob/master/template/config/index.js#L10
```javascript
 variables: path.resolve(__dirname, '../src/themes/quasar.variables.styl'),
```
Is it an oversight ? Or maybe now it work differently?

**Comment by rstoenescu** [comment]
Will look into it.

**Comment by rstoenescu** [comment]
Found the culprit. `variables: resolve(__dirname, 'src/themes/quasar.variables.styl')` should be `variables: resolve('src/themes/quasar.variables.styl')`. Remove the first param (`__dirname`). Will push this fix in a few minutes. Thanks for reporting it!

**Comment by purell** [comment]
Hi @rstoenescu 

I look to the repository this evening but I did not see the updated configuration line. Did you have time to push the modification ? Anyway, I made the change manually on my side and this is now working.

I encountered a problem using Cookie (quasar) module. On 0.14 I was importing it like this
```javascript
import { Cookies } from 'quasar';
```

Now I tried with this
```javascript
import { features } from 'quasar';
const { Cookies } = features;
```
but it does not work much more...


Also, I'm getting a lot of linter (_airbnb-base_) error like this 
```
  83:1  error  'quasar' should be listed in the project's dependencies. Run 'npm i -S quasar' to add it  import/no-extraneous-dependencies
  97:8  error  Unable to resolve path to module 'quasar'                                                 import/no-unresolved
  97:8  error  Missing file extension for "quasar"                                                       import/extensions
```
Did you got this ? From what I understand, we installed `quasar-framework` from **package.json** as
```json
  "dependencies": {
    "quasar-extras": "0.x",
    "quasar-framework": "git+https://git@github.com/quasarframework/quasar-future.git",
  },
```
but we are using `import xxx from 'quasar'` instead of `import xxx from 'quasar-framework'`. This is probably why the linter complained as it does not find the dependencies in the `node_modules`. But in fact we declared an alias in file `webpack.base.conf.js` that SHOULD work but no.
```javascript
    alias: merge(
      {
        quasar: resolve(`node_modules/quasar-framework/dist/quasar.${env.platform.theme}.esm.js`),
      )
```

Is it possible that changes made in file `webpack.base.conf.js` for version 0.15 breaks something between (ESlint --> webpack resolve/aliasl) ? I've noticed that on version 0.14 you include [webpack-merge](https://github.com/quasarframework/quasar-template-default/blob/v0.15-wip/template/build/webpack.base.conf.js#L39) but you did not used it compare to the 0.15 where you use it now. Maybe ESLint is unable to read configuration when enclose in a dynamic function like `merge` ?
Ref ; https://github.com/benmosher/eslint-plugin-import/issues/496

Obviously, I could disable the eslint rules
```
    "import/no-extraneous-dependencies": "off",
    "import/no-unresolved": "off",
    "import/extensions": "off",
    "import/no-unresolved" : "off",
```
but this make no sens :(

**Comment by purell** [comment]
Hi @rstoenescu,

Do you prefer I fill 3 different new issues for 0.15 ?

Best regards,

**Comment by rstoenescu** [comment]
Hi,

Problem #2 is being worked on.
Please fill a ticket for issue #3.
Will investigate issue #1 -- this would go to the starter kit repo.

Thanks for reporting problems!

**Comment by purell** [comment]
Could you keep me informed about the problem #1 and #2 ?

I'm now filling a new ticket for the problem #3, thank you.

**Comment by Boid-John** [comment]
Hello, just wanted to check in on the latest.

Launched my Quasar app at app.boid.com, thanks for this great tool.

**Comment by rstoenescu** [comment]
This repo is already way behind latest v0.15. For the latest you'll need the new starter kit (that will amaze you! -- zero config). I'm not inclined to share it yet, since docs are not ready and it might be misunderstood at the moment.
