### ISSUE TITLE
Live documentation

### ISSUE THREAD

**Issue by nueko** [quasarframework/quasar-future#2]
Hello, what about the live/online documentation?

**Comment by rstoenescu** [comment]
Hi,

I can't work on features and offer them before they are done and also offer documentation. I'm one man working 17 hours a day. 'quasar-future' shouldn't have existed in the first place, but some developers need the new features badly, so I am offering them in alpha stage with this repo. On the official release, there's going to be documentation, Quasar Play updated etc etc. Until then, just clone the main Quasar repo, run "npm run dev" and take a look at the examples (source code in /dev) which should be updated (in 99% of cases) for the new version that's coming out soon.

Sorry for this. All I can say is that the final release will be "ground-breaking" and any wait will be totally worth it. Until then, I can't offer same things for quasar-future as for an official Quasar release, so you'll have to dig in.

**Comment by nueko** [comment]
Wow, 17 hours 😱  I think  You are a super hero, man!

**Comment by rstoenescu** [comment]
I'm not kidding
